
spring:
  datasource:
    url: jdbc:h2:mem:filemanager
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO

filemanager:
  root-path: C:\Users\kh83kh\_Work\stories\dirc-dmd

server:
  port: 8080